django_chats/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from app.views import *

app_name = "app"

urlpatterns = [
    path("", IndexView.as_view(), name="homepage"),
    path("write-post/", CreatePostView.as_view(), name="write_post"),
    path("post/<int:post_id>/like/", toggle_reaction, name="toggle_reaction"),
    path("post/<int:post_id>/comments/", CommentsView.as_view(), name="post_comments"),
    path("edit-post/<int:post_id>/", UpdatePostView.as_view(), name="edit_post"),
    path("profile/<int:profile_id>/", ProfileUserView.as_view(), name="profile"),
    path(
        "edit-profile/<int:profile_id>/",
        UpdateProfileView.as_view(),
        name="edit_profile",
    ),
    path("users/", UsersListView.as_view(), name="users"),
    path("tasks/", TaskListView.as_view(), name="tasks"),
    path("task/<int:task_id>", TaskDetailView.as_view(), name="task_detail"),
    path("edit-task/<int:task_id>", change_task_status, name="edit_task"),
    path("profile/logout/", logout_view, name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_chats/chats/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from chats.views import *

app_name = "chats"

urlpatterns = [
    path("start/<int:user_id>", start_chat, name="start_chat"),
    path("<int:chat_id>/", ChatDetailView.as_view(), name="chat_details"),
    path("all/", ChatListView.as_view(), name="chats_all"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_chats/django_chats/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app.urls", namespace="app")),
    path('chat/',include("chats.urls", namespace="chats")),
    path('login/', include("users.urls", namespace="enter")),
]

django_chats/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Django Chats</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 text-gray-800">
<header class="sticky top-0 bg-white shadow-md">
    <div class="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center">
        <div class="text-2xl font-bold text-blue-600">django-chats</div>
        <div class="flex flex-row gap-2 items-center">
            <img class="h-10 w-10 rounded-full" src="{{ user.get_user_image_url }}" alt="avatar">
            <a href="{% url 'app:profile' user.id %}"><span>{{ user.last_name }} {{ user.first_name }}</span></a>
        </div>
    </div>
</header>

<main class="flex flex-row justify-center items-start mt-8 px-4 w-3/4 mx-auto">
    <div class="flex-none w-1/5">
        {% include 'side_menu.html' %}
    </div>
    <div class="flex flex-grow flex-col gap-5">
        {% block main %}{% endblock %}
    </div>
</main>

</body>
</html>

django_chats/templates/side_menu.html
<nav class="flex flex-col gap-1">
        <a href="{% url 'app:homepage' %}" class="p-2 text-center bg-gray-200 text-xl text-gray-700 hover:text-blue-500 rounded-t-lg">Лента</a>
        <a href="{% url 'chats:chats_all' %}" class="p-2 text-center bg-gray-200 text-xl text-gray-700 hover:text-blue-500">Чаты</a>
        <a href="{% url 'app:tasks' %}" class="p-2 text-center bg-gray-200 text-xl text-gray-700 hover:text-blue-500">Задачи</a>
        <a href="{% url 'app:users' %}" class="p-2 text-center bg-gray-200 text-xl text-gray-700 hover:text-blue-500">Участники</a>
        <a href="{% url 'app:profile' user.id %}" class="p-2 text-center bg-gray-200 text-xl text-gray-700 hover:text-blue-500 rounded-b-lg">Профиль</a>
</nav>