django_chats/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from app.views import *

app_name = "app"

urlpatterns = [
    path("", IndexView.as_view(), name="homepage"),
    path("write-post/", CreatePostView.as_view(), name="write_post"),
    path("post/<int:post_id>/like/", toggle_reaction, name="toggle_reaction"),
    path("post/<int:post_id>/comments/", CommentsView.as_view(), name="post_comments"),
    path("edit-post/<int:post_id>/", UpdatePostView.as_view(), name="edit_post"),
    path("profile/<int:profile_id>/", ProfileUserView.as_view(), name="profile"),
    path(
        "edit-profile/<int:profile_id>/",
        UpdateProfileView.as_view(),
        name="edit_profile",
    ),
    path("users/", UsersListView.as_view(), name="users"),
    path("tasks/", TaskListView.as_view(), name="tasks"),
    path("task/<int:task_id>", TaskDetailView.as_view(), name="task_detail"),
    path("edit-task/<int:task_id>", change_task_status, name="edit_task"),
    path("profile/logout/", logout_view, name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_chats/chats/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from chats.views import *

app_name = "chats"

urlpatterns = [
    path("start/<int:user_id>", start_chat, name="start_chat"),
    path("<int:chat_id>/", ChatDetailView.as_view(), name="chat_details"),
    path("all/", ChatListView.as_view(), name="chats_all"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_chats/django_chats/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app.urls", namespace="app")),
    path('chat/',include("chats.urls", namespace="chats")),
    path('login/', include("users.urls", namespace="enter")),
]

django_chats/chats/models/chat_members.py
from django.db import models

from utils.database.mixins.timestam_mixins import TimeStampMixin


class ChatMember(TimeStampMixin):

    chat = models.ForeignKey(
        "Chat", on_delete=models.CASCADE, related_name="chat_members"
    )

    user = models.ForeignKey(
        "users.CustomUser", on_delete=models.CASCADE, related_name="user_chats"
    )

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("chat", "user")

django_chats/chats/models/chats.py
from django.db import models

from utils.database.mixins.timestam_mixins import TimeStampMixin
from utils.snowflake_helper import get_snowflake_id


class Chat(TimeStampMixin):

    class Meta:
        verbose_name = "чат"
        verbose_name_plural = "Чаты"

    id = models.BigIntegerField(
        primary_key=True, editable=False, default=get_snowflake_id
    )

    title = models.CharField(max_length=256, null=False, blank=False)
    description = models.TextField(null=True)
    is_group = models.BooleanField(default=False)

    def __str__(self):
        if self.title:
            return self.title
        else:
            return "Без названия"

    def users(self):
        members = self.chat_members.select_related("user").all()

        if len(members) == 2:
            return f"{members[0]} & {members[1]}"
        else:
            return f"{members[0]} & {members[1]} & {len(members)-2} more"

django_chats/chats/models/messages.py
from django.db import models

from utils.database.mixins.timestam_mixins import TimeStampMixin


class Messages(TimeStampMixin):

    chat = models.ForeignKey("Chat", on_delete=models.CASCADE, related_name="messages")
    sender = models.ForeignKey(
        "users.CustomUser",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="messages",
    )
    text = models.TextField(null=False)

django_chats/chats/forms/chat_form.py
from django import forms

from chats.models import Messages


class MessageForm(forms.ModelForm):

    text = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "flex-1 border rounded-full px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-400",
                "placeholder": "Напишите сообщение...",
                "type": "text",
                "autocomplete": "off",
            }
        )
    )

    class Meta:
        model = Messages
        fields = ["text"]

django_chats/chats/templates/chats/chat.html
{% extends "base.html" %}
{% load static %}

{% block main %}
<div class="w-4/5 mx-auto bg-white shadow rounded-lg p-6 h-[600px] overflow-y-auto">
    <h2 class="text-xl font-semibold mb-4">Чат с {{ chat_with }}</h2>
    {% if chat_messages %}
    <div class="space-y-4">
        {% for message in chat_messages %}
        {% if message.sender == user %}
        <div class="justify-end flex flex-row gap-4">
            <div class="flex flex-col items-end">
                <p class="bg-blue-500 text-white inline-block px-4 py-2 rounded-lg">
                    {{ message.text }}
                </p>
                <span class="text-sm text-gray-500 mt-1">{{ message.created_at|date:"H:i · d.m.Y" }}</span>
            </div>
            <img class="h-16 w-16 rounded-full shadow-lg" src="{{ message.sender.get_user_image_url }}"
                 alt="Your-Photo">
        </div>
        {% else %}
        <div class="text-left flex flex-row gap-4">
            <img class="h-16 w-16 rounded-full shadow-lg" src="{{ message.sender.get_user_image_url }}"
                 alt="Friend-Photo">
            <div class="flex flex-col items-start">
                <p class="bg-blue-500 text-white inline-block px-4 py-2 rounded-lg">
                    {{ message.text }}
                </p>
                <span class="text-sm text-gray-500 mt-1">{{ message.created_at|date:"H:i · d.m.Y" }}</span>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% else %}
    <div class="h-full w-full space-y-4 flex justify-center items-center">
        <div class="bg-gray-300 rounded-xl p-5 text-left flex flex-row gap-4">
            Нет сообщений с {{ chat_with }}
        </div>
    </div>
    {% endif %}


</div>
<form method="post" class="w-4/5 mx-auto border-t px-4 py-3 flex items-center gap-2">
    {% csrf_token %}
    {{ form.text }}
    <button
            type="submit"
            class="bg-blue-500 text-white px-4 py-2 rounded-full hover:bg-blue-600 transition"
    >
        Отправить
    </button>
</form>

{% endblock %}

django_chats/chats/templates/chats/chat_list.html
{% extends "base.html" %}
{% load static %}

{% block main %}
<div class="w-4/5 mx-auto flex justify-center items-center text-2xl font-bold" style="height:50px; width:800px">
    <h2>Активные чаты</h2>
</div>
<ul>
    {% for obj in object_list %}
    <a href="{% url 'chats:chat_details' obj.id %}" class="ml-auto text-blue-500">
        <li class="w-4/5 mb-5 mx-auto bg-white p-4 rounded-lg shadow flex items-center hover:bg-blue-50 transition">
            <img src="{% if obj.last_sender %}{{ obj.chat_with.get_user_image_url }}{% else %}/static/img/default_image.png{% endif %}"
                 alt="user-avatar" class="w-12 h-12 rounded-full  flex-shrink-0 mr-4">
            <div class="flex-1">
                <h3 class="text-lg font-semibold text-gray-800">{% if obj.is_group %}Группа: {{ obj.title }}{% else %}Чат с {{ obj.last_sender }}{% endif %}</h3>
                <p class="text-sm text-gray-500 truncate">
                    {% if obj.last_message %}<span>{{ obj.last_sender }}:</span> <span>{{ obj.last_message }}{% else %}Нет сообщенией{% endif %}</span>
                </p>
            </div>
        </li>
    </a>
    {% empty %}
    <li class="text-center text-gray-500">Нет доступных чатов</li>
    {% endfor %}
</ul>
{% endblock %}